---
title: "Day 1 - exercises"
author: "Carl Herrmann"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```


Loading the data

```{r}
dat = as_tibble(read.delim('https://tinyurl.com/y4fark9g')) # Load the dataset
```


## Exercise 1

```{r}
head(dat, 10)
```

Same thing with another command:

```{r}
dat[1:10,]
```

Last column:

```{r}
dat[,ncol(dat), drop=FALSE]
```



## Exercise 2


Histogram of cholesterol:

```{r}
ggplot(dat) + geom_histogram(aes(x=chol),binwidth=5)
```

```{r}
dat %>% drop_na(chol) %>% ggplot(aes(x=chol,y=..density..)) + geom_histogram(binwidth=5,fill='red',color='darkred') + geom_density() + labs(title='Cholesterol values',x= 'cholesterol values')
```
2. Only male patients:


```{r}
dat %>% filter(gender=='male') %>% drop_na(chol) %>% ggplot() + geom_histogram(aes(x=chol),binwidth=5,fill='red',color='darkred') + labs(title='Cholesterol values, male patients',x= 'cholesterol values')
```
```{r}
qmale = dat %>% filter(gender=='male') %>% drop_na(chol) %>% pull(chol) %>%  quantile(probs=c(0.25,0.5,0.75))
qfemale = dat %>% filter(gender=='female') %>% drop_na(chol) %>% pull(chol) %>%  quantile(probs=c(0.25,0.5,0.75))


dat %>% filter(gender=='male') %>% drop_na(chol) %>% ggplot() + geom_histogram(aes(x=chol),binwidth=5,fill='red',color='darkred') + geom_vline(xintercept=qmale) + geom_vline(xintercept=qfemale,color='blue') + labs(title='Cholesterol values, male patients',x= 'cholesterol values')
```

Association hip/waist



```{r}
dat %>% drop_na(c(hip,waist)) %>% ggplot() + geom_point(aes(x=hip,y=waist))
```
```{r}
dat %>% drop_na(c(hip,waist)) %>% ggplot() + geom_point(aes(x=rank(hip),y=rank(waist)))
```
```{r}
cor(dat$hip,dat$waist,use = 'complete.obs') # pearson
cor(dat$hip,dat$waist,use='complete.obs',method='spearman') # spearman

```



## Going further


```{r}
all.cor = dat %>% select(where(is.numeric)) %>% drop_na() %>% cor()
```


```{r}
library(pheatmap)

pheatmap(all.cor)
```

Highest/lowest correlations: 

```{r}
## set the diagonal to NA
diag(all.cor) = NA

M = max(all.cor,na.rm=TRUE)
m = min(all.cor,na.rm=TRUE)
```

```{r}
which(all.cor==M,arr.ind=TRUE)
which(all.cor==m,arr.ind=TRUE)
```


