<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 WEEK 1: Hypothesis testing | Bioinformatics introductory course - MSc Molekulare Biotechnologie</title>
  <meta name="description" content="RMarkdowns for the Data Analysis introduction course (SoSe2024), MoBi MA" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="4 WEEK 1: Hypothesis testing | Bioinformatics introductory course - MSc Molekulare Biotechnologie" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="RMarkdowns for the Data Analysis introduction course (SoSe2024), MoBi MA" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 WEEK 1: Hypothesis testing | Bioinformatics introductory course - MSc Molekulare Biotechnologie" />
  
  <meta name="twitter:description" content="RMarkdowns for the Data Analysis introduction course (SoSe2024), MoBi MA" />
  

<meta name="author" content="Biomedical Genomics group, IPMB" />


<meta name="date" content="2024-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-1-probability-distributions.html"/>
<link rel="next" href="week-1-multiple-testing-and-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioinformatics Introduction course (MoBi MA)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#where-to-start"><i class="fa fa-check"></i>Where to start</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i>R</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#rstudio"><i class="fa fa-check"></i>RStudio</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#variable-assignment-in-r"><i class="fa fa-check"></i>Variable assignment in R</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#classes"><i class="fa fa-check"></i>Classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#logical-operations"><i class="fa fa-check"></i>Logical operations</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#vectors"><i class="fa fa-check"></i>Vectors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#matrixes"><i class="fa fa-check"></i>Matrixes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dataframes"><i class="fa fa-check"></i>Dataframes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-markdown"><i class="fa fa-check"></i>R Markdown</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#advanced-data-manipulation-with-tidyverse"><i class="fa fa-check"></i>Advanced data manipulation with tidyverse</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#filter-based-on-conditions"><i class="fa fa-check"></i>Filter based on conditions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#select-specific-columns"><i class="fa fa-check"></i>Select specific columns</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#operations-on-groups"><i class="fa fa-check"></i>Operations on groups</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#pretty-plots-using-ggplot2"><i class="fa fa-check"></i>Pretty plots using ggplot2</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#histogram"><i class="fa fa-check"></i>Histogram</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#scatter-plot"><i class="fa fa-check"></i>Scatter plot</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#boxplot"><i class="fa fa-check"></i>Boxplot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html"><i class="fa fa-check"></i><b>1</b> WEEK 1: Descriptive statistics and data types</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#data-features-and-where-to-find-them"><i class="fa fa-check"></i><b>1.1</b> Data features and where to find them</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#load-the-data"><i class="fa fa-check"></i><b>1.1.1</b> Load the data</a></li>
<li class="chapter" data-level="1.1.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#dimensions-and-naming"><i class="fa fa-check"></i><b>1.1.2</b> Dimensions and naming</a></li>
<li class="chapter" data-level="1.1.3" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#numerical-features"><i class="fa fa-check"></i><b>1.1.3</b> Numerical features</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#data-cleaning"><i class="fa fa-check"></i><b>1.2</b> Data cleaning</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#filter"><i class="fa fa-check"></i><b>1.2.1</b> filter()</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#is.na"><i class="fa fa-check"></i><b>1.2.2</b> is.na()</a></li>
<li class="chapter" data-level="1.2.3" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#mutate"><i class="fa fa-check"></i><b>1.2.3</b> mutate()</a></li>
<li class="chapter" data-level="1.2.4" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#accross"><i class="fa fa-check"></i><b>1.2.4</b> accross()</a></li>
<li class="chapter" data-level="1.2.5" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#in"><i class="fa fa-check"></i><b>1.2.5</b> %in%</a></li>
<li class="chapter" data-level="1.2.6" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#ready-for-the-cleaning"><i class="fa fa-check"></i><b>1.2.6</b> Ready for the cleaning!</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#visualizing-data-distribution"><i class="fa fa-check"></i><b>1.3</b> Visualizing data distribution</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#histograms"><i class="fa fa-check"></i><b>1.3.1</b> Histograms</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#density-plots"><i class="fa fa-check"></i><b>1.3.2</b> Density plots</a></li>
<li class="chapter" data-level="1.3.3" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#boxplots"><i class="fa fa-check"></i><b>1.3.3</b> Boxplots</a></li>
<li class="chapter" data-level="1.3.4" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#qq-plots"><i class="fa fa-check"></i><b>1.3.4</b> QQ-plots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#correlation"><i class="fa fa-check"></i><b>1.4</b> Correlation</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#measuring-the-centrality-in-data"><i class="fa fa-check"></i><b>1.4.1</b> Measuring the centrality in data</a></li>
<li class="chapter" data-level="1.4.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#association-between-variables"><i class="fa fa-check"></i><b>1.4.2</b> Association between variables</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#exercises"><i class="fa fa-check"></i><b>1.5</b> EXERCISES</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#exercise-1-data-features"><i class="fa fa-check"></i><b>1.5.1</b> Exercise 1: Data features</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#exercise-2-visualization"><i class="fa fa-check"></i><b>1.5.2</b> Exercise 2: Visualization</a></li>
<li class="chapter" data-level="1.5.3" data-path="week-1-descriptive-statistics-and-data-types.html"><a href="week-1-descriptive-statistics-and-data-types.html#exercise-3-correlation"><i class="fa fa-check"></i><b>1.5.3</b> Exercise 3: Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html"><i class="fa fa-check"></i><b>2</b> WEEK 1: Dimensionality reduction and unsupervised learning</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#preparing-the-data"><i class="fa fa-check"></i><b>2.1</b> Preparing the data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#load-data"><i class="fa fa-check"></i><b>2.1.1</b> Load data</a></li>
<li class="chapter" data-level="2.1.2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#data-transformation"><i class="fa fa-check"></i><b>2.1.2</b> Data transformation</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#k-means-clustering"><i class="fa fa-check"></i><b>2.2</b> k-means clustering</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#performing-k-means"><i class="fa fa-check"></i><b>2.2.1</b> Performing k-means</a></li>
<li class="chapter" data-level="2.2.2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#quality-of-the-clustering"><i class="fa fa-check"></i><b>2.2.2</b> Quality of the clustering</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#hierarchical-clustering"><i class="fa fa-check"></i><b>2.3</b> Hierarchical clustering</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#determine-the-most-variable-genes"><i class="fa fa-check"></i><b>2.3.1</b> Determine the most variable genes</a></li>
<li class="chapter" data-level="2.3.2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#computing-the-correlation-between-all-patients"><i class="fa fa-check"></i><b>2.3.2</b> Computing the correlation between all patients</a></li>
<li class="chapter" data-level="2.3.3" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#including-clinical-annotations-in-the-heatmap"><i class="fa fa-check"></i><b>2.3.3</b> Including clinical annotations in the heatmap</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#principal-component-analysis"><i class="fa fa-check"></i><b>2.4</b> Principal component analysis</a></li>
<li class="chapter" data-level="2.5" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#exercises-1"><i class="fa fa-check"></i><b>2.5</b> EXERCISES</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#exercise-1-variance"><i class="fa fa-check"></i><b>2.5.1</b> Exercise 1: Variance</a></li>
<li class="chapter" data-level="2.5.2" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#exercise-2-hierarchical-clustering"><i class="fa fa-check"></i><b>2.5.2</b> Exercise 2: Hierarchical clustering</a></li>
<li class="chapter" data-level="2.5.3" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#exercise-3-pca"><i class="fa fa-check"></i><b>2.5.3</b> Exercise 3: PCA</a></li>
<li class="chapter" data-level="2.5.4" data-path="week-1-dimensionality-reduction-and-unsupervised-learning.html"><a href="week-1-dimensionality-reduction-and-unsupervised-learning.html#going-further-expert"><i class="fa fa-check"></i><b>2.5.4</b> Going further <em>(expert)</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html"><i class="fa fa-check"></i><b>3</b> WEEK 1: Probability distributions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#probability-distributions"><i class="fa fa-check"></i><b>3.1</b> Probability distributions</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#getting-to-know-the-various-functions"><i class="fa fa-check"></i><b>3.1.1</b> Getting to know the various functions</a></li>
<li class="chapter" data-level="3.1.2" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#normalgaussian-distribution"><i class="fa fa-check"></i><b>3.1.2</b> Normal/Gaussian distribution</a></li>
<li class="chapter" data-level="3.1.3" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#visualization"><i class="fa fa-check"></i><b>3.1.3</b> Visualization</a></li>
<li class="chapter" data-level="3.1.4" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#application-on-a-real-dataset"><i class="fa fa-check"></i><b>3.1.4</b> Application on a real dataset</a></li>
<li class="chapter" data-level="3.1.5" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#binomial-distribution"><i class="fa fa-check"></i><b>3.1.5</b> Binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#confidence-interval"><i class="fa fa-check"></i><b>3.2</b> Confidence interval</a></li>
<li class="chapter" data-level="3.3" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#exercises-2"><i class="fa fa-check"></i><b>3.3</b> EXERCISES</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#exercise-1-probability-distributions"><i class="fa fa-check"></i><b>3.3.1</b> Exercise 1: Probability distributions</a></li>
<li class="chapter" data-level="3.3.2" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#exercise-2-binomial-distribution"><i class="fa fa-check"></i><b>3.3.2</b> Exercise 2: Binomial distribution</a></li>
<li class="chapter" data-level="3.3.3" data-path="week-1-probability-distributions.html"><a href="week-1-probability-distributions.html#exercise-3-confidence-intervals"><i class="fa fa-check"></i><b>3.3.3</b> Exercise 3: Confidence intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html"><i class="fa fa-check"></i><b>4</b> WEEK 1: Hypothesis testing</a>
<ul>
<li class="chapter" data-level="4.0.1" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>4.0.1</b> One sample t-test</a></li>
<li class="chapter" data-level="4.0.2" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#two-sample-t-test-2-sided"><i class="fa fa-check"></i><b>4.0.2</b> Two-sample t-test (2-sided)</a></li>
<li class="chapter" data-level="4.0.3" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#two-sample-t-test-1-sided"><i class="fa fa-check"></i><b>4.0.3</b> Two-sample t-test (1-sided)</a></li>
<li class="chapter" data-level="4.1" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#exercises-3"><i class="fa fa-check"></i><b>4.1</b> EXERCISES</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#exercise-1-one-sided-t-test"><i class="fa fa-check"></i><b>4.1.1</b> Exercise 1: One-sided t-test</a></li>
<li class="chapter" data-level="4.1.2" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#exercice-2-two-sided-t-test"><i class="fa fa-check"></i><b>4.1.2</b> Exercice 2: Two-sided t-test</a></li>
<li class="chapter" data-level="4.1.3" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#exercise-3.-going-further-checking-the-normality-of-the-distribution"><i class="fa fa-check"></i><b>4.1.3</b> Exercise 3. Going further … Checking the normality of the distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#wilcoxon-test"><i class="fa fa-check"></i><b>4.2</b> Wilcoxon test</a></li>
<li class="chapter" data-level="4.3" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#chi-squared-test"><i class="fa fa-check"></i><b>4.3</b> Chi-squared test</a></li>
<li class="chapter" data-level="4.4" data-path="week-1-hypothesis-testing.html"><a href="week-1-hypothesis-testing.html#fishers-exact-test"><i class="fa fa-check"></i><b>4.4</b> Fisher’s exact test</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-1-multiple-testing-and-regression.html"><a href="week-1-multiple-testing-and-regression.html"><i class="fa fa-check"></i><b>5</b> WEEK 1: Multiple testing and regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-1-multiple-testing-and-regression.html"><a href="week-1-multiple-testing-and-regression.html#multiple-testing"><i class="fa fa-check"></i><b>5.1</b> Multiple testing</a></li>
<li class="chapter" data-level="5.2" data-path="week-1-multiple-testing-and-regression.html"><a href="week-1-multiple-testing-and-regression.html#regression"><i class="fa fa-check"></i><b>5.2</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-2-annotathon.html"><a href="week-2-annotathon.html"><i class="fa fa-check"></i><b>6</b> WEEK 2: Annotathon!</a></li>
<li class="chapter" data-level="7" data-path="week-2-data-formats-and-where-to-find-them.html"><a href="week-2-data-formats-and-where-to-find-them.html"><i class="fa fa-check"></i><b>7</b> WEEK 2: Data formats and where to find them</a></li>
<li class="chapter" data-level="8" data-path="week-2-rna-seq---from-fastq-to-count-matrix.html"><a href="week-2-rna-seq---from-fastq-to-count-matrix.html"><i class="fa fa-check"></i><b>8</b> WEEK 2: RNA-seq - from FASTQ to count matrix</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="9" data-path="instructions.html"><a href="instructions.html"><i class="fa fa-check"></i><b>9</b> instructions</a>
<ul>
<li class="chapter" data-level="9.1" data-path="instructions.html"><a href="instructions.html#chapters-and-sub-chapters"><i class="fa fa-check"></i><b>9.1</b> Chapters and sub-chapters</a></li>
<li class="chapter" data-level="9.2" data-path="instructions.html"><a href="instructions.html#captioned-figures-and-tables"><i class="fa fa-check"></i><b>9.2</b> Captioned figures and tables</a></li>
<li class="chapter" data-level="9.3" data-path="instructions.html"><a href="instructions.html#footnotes"><i class="fa fa-check"></i><b>9.3</b> Footnotes</a></li>
<li class="chapter" data-level="9.4" data-path="instructions.html"><a href="instructions.html#citations"><i class="fa fa-check"></i><b>9.4</b> Citations</a></li>
<li class="chapter" data-level="9.5" data-path="instructions.html"><a href="instructions.html#equations"><i class="fa fa-check"></i><b>9.5</b> Equations</a></li>
<li class="chapter" data-level="9.6" data-path="instructions.html"><a href="instructions.html#theorems-and-proofs"><i class="fa fa-check"></i><b>9.6</b> Theorems and proofs</a></li>
<li class="chapter" data-level="9.7" data-path="instructions.html"><a href="instructions.html#callout-blocks"><i class="fa fa-check"></i><b>9.7</b> Callout blocks</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bioinformatics introductory course - MSc Molekulare Biotechnologie</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-1-hypothesis-testing" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> WEEK 1: Hypothesis testing<a href="week-1-hypothesis-testing.html#week-1-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>On this section, we will go through hypothesis testing. You will start to see how to <em>formulate hypotheses</em> and how to <em>test</em> them.
In addition, we want to learn how to use and interpret hypothesis tests.</p>
<p>We will work again with the diabetes dataset that we used previously.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="week-1-hypothesis-testing.html#cb200-1" tabindex="-1"></a>dat <span class="ot">=</span> <span class="fu">read.delim</span>(<span class="st">&#39;https://tinyurl.com/y4fark9g&#39;</span>)</span>
<span id="cb200-2"><a href="week-1-hypothesis-testing.html#cb200-2" tabindex="-1"></a></span>
<span id="cb200-3"><a href="week-1-hypothesis-testing.html#cb200-3" tabindex="-1"></a><span class="co"># set the row names using the column id</span></span>
<span id="cb200-4"><a href="week-1-hypothesis-testing.html#cb200-4" tabindex="-1"></a><span class="fu">rownames</span>(dat) <span class="ot">=</span> dat<span class="sc">$</span>id</span></code></pre></div>
<p>Load the required packages</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="week-1-hypothesis-testing.html#cb201-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb201-2"><a href="week-1-hypothesis-testing.html#cb201-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Check out the content of the dataset using the summary function</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="week-1-hypothesis-testing.html#cb202-1" tabindex="-1"></a><span class="fu">summary</span>(dat)</span></code></pre></div>
<pre><code>##        id             chol          stab.glu          hdl        
##  Min.   : 1000   Min.   : 78.0   Min.   : 48.0   Min.   : 12.00  
##  1st Qu.: 4792   1st Qu.:179.0   1st Qu.: 81.0   1st Qu.: 38.00  
##  Median :15766   Median :204.0   Median : 89.0   Median : 46.00  
##  Mean   :15978   Mean   :207.8   Mean   :106.7   Mean   : 50.45  
##  3rd Qu.:20336   3rd Qu.:230.0   3rd Qu.:106.0   3rd Qu.: 59.00  
##  Max.   :41756   Max.   :443.0   Max.   :385.0   Max.   :120.00  
##                  NA&#39;s   :1                       NA&#39;s   :1       
##      ratio            glyhb         location              age       
##  Min.   : 1.500   Min.   : 2.68   Length:403         Min.   :19.00  
##  1st Qu.: 3.200   1st Qu.: 4.38   Class :character   1st Qu.:34.00  
##  Median : 4.200   Median : 4.84   Mode  :character   Median :45.00  
##  Mean   : 4.522   Mean   : 5.59                      Mean   :46.85  
##  3rd Qu.: 5.400   3rd Qu.: 5.60                      3rd Qu.:60.00  
##  Max.   :19.300   Max.   :16.11                      Max.   :92.00  
##  NA&#39;s   :1        NA&#39;s   :13                                        
##     gender              height          weight         frame          
##  Length:403         Min.   :52.00   Min.   : 99.0   Length:403        
##  Class :character   1st Qu.:63.00   1st Qu.:151.0   Class :character  
##  Mode  :character   Median :66.00   Median :172.5   Mode  :character  
##                     Mean   :66.02   Mean   :177.6                     
##                     3rd Qu.:69.00   3rd Qu.:200.0                     
##                     Max.   :76.00   Max.   :325.0                     
##                     NA&#39;s   :5       NA&#39;s   :1                         
##      bp.1s           bp.1d            bp.2s           bp.2d       
##  Min.   : 90.0   Min.   : 48.00   Min.   :110.0   Min.   : 60.00  
##  1st Qu.:121.2   1st Qu.: 75.00   1st Qu.:138.0   1st Qu.: 84.00  
##  Median :136.0   Median : 82.00   Median :149.0   Median : 92.00  
##  Mean   :136.9   Mean   : 83.32   Mean   :152.4   Mean   : 92.52  
##  3rd Qu.:146.8   3rd Qu.: 90.00   3rd Qu.:161.0   3rd Qu.:100.00  
##  Max.   :250.0   Max.   :124.00   Max.   :238.0   Max.   :124.00  
##  NA&#39;s   :5       NA&#39;s   :5        NA&#39;s   :262     NA&#39;s   :262     
##      waist           hip           time.ppn     
##  Min.   :26.0   Min.   :30.00   Min.   :   5.0  
##  1st Qu.:33.0   1st Qu.:39.00   1st Qu.:  90.0  
##  Median :37.0   Median :42.00   Median : 240.0  
##  Mean   :37.9   Mean   :43.04   Mean   : 341.2  
##  3rd Qu.:41.0   3rd Qu.:46.00   3rd Qu.: 517.5  
##  Max.   :56.0   Max.   :64.00   Max.   :1560.0  
##  NA&#39;s   :2      NA&#39;s   :2       NA&#39;s   :3</code></pre>
<p>How can we inspect the differences between the weight of men and women? We can start by ploting two histograms or density plots representing the weight by biological sex.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="week-1-hypothesis-testing.html#cb204-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat,</span>
<span id="cb204-2"><a href="week-1-hypothesis-testing.html#cb204-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> weight, </span>
<span id="cb204-3"><a href="week-1-hypothesis-testing.html#cb204-3" tabindex="-1"></a>           <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb204-4"><a href="week-1-hypothesis-testing.html#cb204-4" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<p>The distributions look different in shape, right? Where do you think the mean would be located in the plot?</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="week-1-hypothesis-testing.html#cb205-1" tabindex="-1"></a><span class="co"># We can use &quot;filter()&quot; to filter the cholesterol values for men and women</span></span>
<span id="cb205-2"><a href="week-1-hypothesis-testing.html#cb205-2" tabindex="-1"></a>dat.male <span class="ot">=</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb205-3"><a href="week-1-hypothesis-testing.html#cb205-3" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">&#39;male&#39;</span>)</span>
<span id="cb205-4"><a href="week-1-hypothesis-testing.html#cb205-4" tabindex="-1"></a></span>
<span id="cb205-5"><a href="week-1-hypothesis-testing.html#cb205-5" tabindex="-1"></a>dat.female <span class="ot">=</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb205-6"><a href="week-1-hypothesis-testing.html#cb205-6" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">&#39;female&#39;</span>)</span>
<span id="cb205-7"><a href="week-1-hypothesis-testing.html#cb205-7" tabindex="-1"></a></span>
<span id="cb205-8"><a href="week-1-hypothesis-testing.html#cb205-8" tabindex="-1"></a><span class="co"># we will calculate the mean weight by sex.</span></span>
<span id="cb205-9"><a href="week-1-hypothesis-testing.html#cb205-9" tabindex="-1"></a>mean.men <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat.male<span class="sc">$</span>weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb205-10"><a href="week-1-hypothesis-testing.html#cb205-10" tabindex="-1"></a>mean.women <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat.female<span class="sc">$</span>weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>And we can then add in the means to the plot as vertical lines.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="week-1-hypothesis-testing.html#cb206-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat,</span>
<span id="cb206-2"><a href="week-1-hypothesis-testing.html#cb206-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> weight, </span>
<span id="cb206-3"><a href="week-1-hypothesis-testing.html#cb206-3" tabindex="-1"></a>           <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb206-4"><a href="week-1-hypothesis-testing.html#cb206-4" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb206-5"><a href="week-1-hypothesis-testing.html#cb206-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.men, <span class="at">colour =</span> <span class="st">&quot;cyan&quot;</span>) <span class="sc">+</span></span>
<span id="cb206-6"><a href="week-1-hypothesis-testing.html#cb206-6" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.women, <span class="at">colour =</span> <span class="st">&quot;salmon&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-112-1.png" width="672" /></p>
<blockquote>
<p>Do you think that the mean of the male weight is lower than 180?
Do you think that the mean of the female weight is <strong>really</strong> different from the mean of the male weights?
Do you think that the mean of the male weight is higher than that of the females?</p>
</blockquote>
<hr />
<p>Now, we want to use a statistical test to check if,</p>
<ul>
<li>males have a mean weight that is <strong>significantly</strong> lower than a specific value (one-sample, one-tailed test)</li>
<li>there is a <strong>significant</strong> difference in the mean of the weights between the two groups (two-sample, two-sided test)</li>
<li>male have a <strong>significantly</strong> higher mean weight than females (two-sample, one-sided test)</li>
</ul>
<p>Note the use of the word <strong>significant</strong> in the previous statements!</p>
<p>This is exactly what <strong>mean tests</strong> such as the t-test (or the Wilcoxon test) are designed for!
We will perform here a <strong>t-test</strong>.</p>
<div id="one-sample-t-test" class="section level3 hasAnchor" number="4.0.1">
<h3><span class="header-section-number">4.0.1</span> One sample t-test<a href="week-1-hypothesis-testing.html#one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using a one-sample t-test, we can check if values differ significantly from a target value.
For example, you could sample 10 chocolate bars, and test if they significantly differ from the expected weight of 100 g:</p>
<blockquote>
<p>Should we perform a one- or two-sided test?</p>
</blockquote>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="week-1-hypothesis-testing.html#cb207-1" tabindex="-1"></a>bars <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">103</span>,<span class="dv">103</span>,<span class="dv">97</span>,<span class="fl">102.5</span>,<span class="fl">100.5</span>,<span class="dv">103</span>,<span class="fl">101.3</span>,<span class="fl">99.5</span>,<span class="dv">101</span>,<span class="dv">104</span>) <span class="co"># weights of 10 chocolate bars</span></span>
<span id="cb207-2"><a href="week-1-hypothesis-testing.html#cb207-2" tabindex="-1"></a>chocbar.mean <span class="ot">=</span> <span class="dv">100</span> <span class="co"># expected weight</span></span></code></pre></div>
<p>The function <code>t.test()</code> offers three <strong>alternative</strong> options: <em>two.sided</em>, <em>less</em> and <em>greater</em>.
Here, if we want to test whether the mean weight of the 10 chocolate bars is <strong>different</strong> from the expected weight of 100 g, we want to perform a <em>two sided</em> test and use the alternative <em>two.sided</em>.</p>
<p>It is essential to <strong>clearly formulate the H0 and H1 hypothesis</strong>.
There are two alternative but equivalent ways to do so.
Either:</p>
<p>&gt; H0: the expectation value of the random variable “Weight of a chocolate bar” is <strong>equal</strong> to 100 g.<br />
</p>
<p>&gt; H1: the expectation value of the random variable “Weight of a chocolate bar” is <strong>different</strong> from 100 g.</p>
<p>or</p>
<p>&gt; H0: the mean weight of a chocolate bar is not significantly different from 100 g.<br />
</p>
<p>&gt; H1: the mean weight of a chocolate bar is significantly different from 100 g.</p>
<p>Note the difference between these two formulations, and ask for help if you have questions about this!</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="week-1-hypothesis-testing.html#cb208-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> bars, <span class="at">mu =</span> chocbar.mean, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  bars
## t = 2.233, df = 9, p-value = 0.05244
## alternative hypothesis: true mean is not equal to 100
## 95 percent confidence interval:
##   99.98067 102.97933
## sample estimates:
## mean of x 
##    101.48</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="week-1-hypothesis-testing.html#cb210-1" tabindex="-1"></a><span class="co"># equivalent to:</span></span>
<span id="cb210-2"><a href="week-1-hypothesis-testing.html#cb210-2" tabindex="-1"></a><span class="co"># t.test(bars,mu = chocbar.mean)</span></span>
<span id="cb210-3"><a href="week-1-hypothesis-testing.html#cb210-3" tabindex="-1"></a><span class="co"># &quot;alternative&quot; is set to &quot;two.sided&quot; per default.</span></span>
<span id="cb210-4"><a href="week-1-hypothesis-testing.html#cb210-4" tabindex="-1"></a></span>
<span id="cb210-5"><a href="week-1-hypothesis-testing.html#cb210-5" tabindex="-1"></a><span class="co"># x is a vector containing the data values</span></span>
<span id="cb210-6"><a href="week-1-hypothesis-testing.html#cb210-6" tabindex="-1"></a><span class="co"># mu indicates the true value of the mean (here: 100g)</span></span></code></pre></div>
<blockquote>
<p>How would you interpret this result?
Can you reject the H0 hypothesis?</p>
</blockquote>
<p>Using alpha = 0.05, the H0 hypothesis can not be rejected as the p-value is 0.05244 (p-value &gt;= 0.05).
With alpha = 0.05, the mean weight of the chocolate bars is not significantly different from 100 g.</p>
<p>Using alpha = 0.1, the H0 hypothesis can be rejected (p-value &lt; 0.1).
With alpha = 0.1, the mean weight of the chocolate bars is significantly different from 100 g.</p>
<p><strong>BUT</strong> … It does not mean that alpha should be chosen with respect to the results of the t.test!!!</p>
<p>Before running a t.test, <strong>formulate the null hypothesis H0 and the alternative hypothesis H1</strong> and <strong>decide about the alpha</strong> value.
Remember, <strong>alpha</strong> represent the <strong>false positive rate</strong>: under the H0 hypothesis (test of two identical distributions), this is the proportion of tests that will detect a difference between the two groups (p-value &lt; alpha).</p>
<p><strong>Beware not to get confused between one-/two-sample tests, and one-/two-sided tests!</strong></p>
<p>Regarding the mean weight of the males, we would like to check whether males have a mean weight that is significantly <strong>lower</strong> than 180.
Here as well, we will perform a <strong>one-sample test</strong>, with mu = 180.
However, we will perform a <strong>one-sided</strong> test using the alternative option <strong>less</strong>.</p>
<p>The hypotheses can be formulated as:<br />
&gt; H0: the expectation value of the random variable “Weight of male patients” is <strong>equal or greater</strong> 180.<br />
</p>
<p>&gt; H1: the expectation value of the random variable “Weight of male patients” is <strong>less</strong> than 180.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="week-1-hypothesis-testing.html#cb211-1" tabindex="-1"></a><span class="fu">t.test</span>(dat.male<span class="sc">$</span>weight, <span class="at">mu =</span> <span class="dv">180</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  dat.male$weight
## t = 0.64094, df = 167, p-value = 0.7388
## alternative hypothesis: true mean is less than 180
## 95 percent confidence interval:
##      -Inf 186.8629
## sample estimates:
## mean of x 
##  181.9167</code></pre>
<blockquote>
<p>How would you interpret the result with alpha = 0.05?
Can you reject the H0 hypothesis?</p>
</blockquote>
</div>
<div id="two-sample-t-test-2-sided" class="section level3 hasAnchor" number="4.0.2">
<h3><span class="header-section-number">4.0.2</span> Two-sample t-test (2-sided)<a href="week-1-hypothesis-testing.html#two-sample-t-test-2-sided" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, we will compare the mean of the weights between males and females.<br />
</p>
<p>According to the previous histogram, females have a different mean weight as males.
This can be tested using a <em>two-sample and two.tailed</em> t.test.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="week-1-hypothesis-testing.html#cb213-1" tabindex="-1"></a><span class="fu">ggplot</span>(dat,</span>
<span id="cb213-2"><a href="week-1-hypothesis-testing.html#cb213-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> weight, </span>
<span id="cb213-3"><a href="week-1-hypothesis-testing.html#cb213-3" tabindex="-1"></a>           <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb213-4"><a href="week-1-hypothesis-testing.html#cb213-4" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb213-5"><a href="week-1-hypothesis-testing.html#cb213-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.men, <span class="at">colour =</span> <span class="st">&quot;cyan&quot;</span>) <span class="sc">+</span></span>
<span id="cb213-6"><a href="week-1-hypothesis-testing.html#cb213-6" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.women, <span class="at">colour =</span> <span class="st">&quot;salmon&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p>The hypotheses can be formulated as:<br />
&gt; H0: the expectation value of the random variable “Weight of male patients” is <strong>equal</strong> to the expectation value of the random variable “Weight of female patients”.<br />
</p>
<p>&gt; H1: the expectation value of the random variable “Weight of male patients” is <strong>different</strong> from the expectation value of the random variable “Weight of female patients”.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="week-1-hypothesis-testing.html#cb214-1" tabindex="-1"></a><span class="fu">t.test</span>(dat.male<span class="sc">$</span>weight, </span>
<span id="cb214-2"><a href="week-1-hypothesis-testing.html#cb214-2" tabindex="-1"></a>       dat.female<span class="sc">$</span>weight)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  dat.male$weight and dat.female$weight
## t = 1.8453, df = 372.45, p-value = 0.06579
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.4875828 15.3465572
## sample estimates:
## mean of x mean of y 
##  181.9167  174.4872</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="week-1-hypothesis-testing.html#cb216-1" tabindex="-1"></a><span class="co"># remember, alternative = &quot;two.sided&quot; per default.</span></span></code></pre></div>
<blockquote>
<p>How would you interpret the result with alpha = 0.05?
Can you reject the H0 hypothesis?</p>
</blockquote>
</div>
<div id="two-sample-t-test-1-sided" class="section level3 hasAnchor" number="4.0.3">
<h3><span class="header-section-number">4.0.3</span> Two-sample t-test (1-sided)<a href="week-1-hypothesis-testing.html#two-sample-t-test-1-sided" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Looking at the histogram, other observers could in principle see a difference between the mean values of the weights and formulate the following hypotheses:</p>
<p>&gt; H0: the expectation value of the random variable “Weight of male patients” is <strong>equal or lower</strong> to the expectation value of the random variable “Weight of female patients”.<br />
</p>
<p>&gt; H1: the expectation value of the random variable “Weight of male patients” is <strong>higher</strong> than the expectation value of the random variable “Weight of female patients”.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="week-1-hypothesis-testing.html#cb217-1" tabindex="-1"></a><span class="fu">t.test</span>(dat.male<span class="sc">$</span>weight, </span>
<span id="cb217-2"><a href="week-1-hypothesis-testing.html#cb217-2" tabindex="-1"></a>       dat.female<span class="sc">$</span>weight, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  dat.male$weight and dat.female$weight
## t = 1.8453, df = 372.45, p-value = 0.0329
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  0.7903498       Inf
## sample estimates:
## mean of x mean of y 
##  181.9167  174.4872</code></pre>
<blockquote>
<p>How would you interpret the result with alpha = 0.05?</p>
</blockquote>
<blockquote>
<p>Can you explain why the p-value of the one-tailed t.test is lower than the p-value of the two-tailed t.test?
What is the relation between these two values?</p>
</blockquote>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="week-1-hypothesis-testing.html#cb219-1" tabindex="-1"></a><span class="co"># p-value of the two-sided t-test versus p-value of the one-sided t-test: </span></span>
<span id="cb219-2"><a href="week-1-hypothesis-testing.html#cb219-2" tabindex="-1"></a><span class="fu">t.test</span>(dat.male<span class="sc">$</span>weight, </span>
<span id="cb219-3"><a href="week-1-hypothesis-testing.html#cb219-3" tabindex="-1"></a>       dat.female<span class="sc">$</span>weight, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)<span class="sc">$</span>p.value <span class="co"># two-tailed</span></span></code></pre></div>
<pre><code>## [1] 0.06579432</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="week-1-hypothesis-testing.html#cb221-1" tabindex="-1"></a><span class="fu">t.test</span>(dat.male<span class="sc">$</span>weight, </span>
<span id="cb221-2"><a href="week-1-hypothesis-testing.html#cb221-2" tabindex="-1"></a>       dat.female<span class="sc">$</span>weight, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)<span class="sc">$</span>p.value <span class="co"># one-tailed</span></span></code></pre></div>
<pre><code>## [1] 0.03289716</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="week-1-hypothesis-testing.html#cb223-1" tabindex="-1"></a><span class="co"># divide the one by the other and see ... </span></span></code></pre></div>
<p>This can be visualized using the t-distribution.
Here (see above result of the t.test), <em>t = 1.8453</em> and <em>df = 372.45</em>.</p>
<p>In the <strong>one-tailed t.test</strong>, the p-value is the area under the curve for t &gt; 1.8453 (alternative greater) <strong>OR</strong> for t &lt; -1.8453 (alternative less).</p>
<p><img src="_main_files/figure-html/unnamed-chunk-120-1.png" width="480" /></p>
<p>In the <strong>two-tailed t.test</strong>, the p-value is the area under the curve for t &gt; 1.8453 (alternative greater) <strong>AND</strong> for t &lt; -1.8453 (alternative less).
It is two times the p-value of the one-sided t.test!</p>
<p><img src="_main_files/figure-html/unnamed-chunk-121-1.png" width="480" /></p>
<p>IMPORTANTLY, a t-test can only be performed if the data is <strong>normally distributed</strong>!
We haven’t check that yet for our dataset … This is the topic of the section <strong>going further</strong> below.</p>
<hr />
</div>
<div id="exercises-3" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> EXERCISES<a href="week-1-hypothesis-testing.html#exercises-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-1-one-sided-t-test" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Exercise 1: One-sided t-test<a href="week-1-hypothesis-testing.html#exercise-1-one-sided-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Consider the following graph, formulate the hypotheses H0 and H1 and perform a (one-sided) t-test.
Interpret the result using alpha = 0.05.</li>
</ol>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="week-1-hypothesis-testing.html#cb224-1" tabindex="-1"></a>mean.height.f <span class="ot">=</span> <span class="fu">mean</span>(dat.female<span class="sc">$</span>height, <span class="at">na.rm =</span> T)</span>
<span id="cb224-2"><a href="week-1-hypothesis-testing.html#cb224-2" tabindex="-1"></a>mean.height.m <span class="ot">=</span> <span class="fu">mean</span>(dat.male<span class="sc">$</span>height, <span class="at">na.rm =</span> T)</span>
<span id="cb224-3"><a href="week-1-hypothesis-testing.html#cb224-3" tabindex="-1"></a></span>
<span id="cb224-4"><a href="week-1-hypothesis-testing.html#cb224-4" tabindex="-1"></a><span class="fu">ggplot</span>(dat,</span>
<span id="cb224-5"><a href="week-1-hypothesis-testing.html#cb224-5" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> height, </span>
<span id="cb224-6"><a href="week-1-hypothesis-testing.html#cb224-6" tabindex="-1"></a>           <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb224-7"><a href="week-1-hypothesis-testing.html#cb224-7" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb224-8"><a href="week-1-hypothesis-testing.html#cb224-8" tabindex="-1"></a>                 <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb224-9"><a href="week-1-hypothesis-testing.html#cb224-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.height.m, </span>
<span id="cb224-10"><a href="week-1-hypothesis-testing.html#cb224-10" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">&quot;cyan&quot;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>,</span>
<span id="cb224-11"><a href="week-1-hypothesis-testing.html#cb224-11" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb224-12"><a href="week-1-hypothesis-testing.html#cb224-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean.height.f, </span>
<span id="cb224-13"><a href="week-1-hypothesis-testing.html#cb224-13" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">&quot;salmon&quot;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>,</span>
<span id="cb224-14"><a href="week-1-hypothesis-testing.html#cb224-14" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-122-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the mean age of the men.</li>
<li>Compare it to age = 50. Formulate the hypotheses H0 and H1 and perform a (one-sided) t-test. Interpret the result using alpha = 0.05.</li>
</ol>
</div>
<div id="exercice-2-two-sided-t-test" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Exercice 2: Two-sided t-test<a href="week-1-hypothesis-testing.html#exercice-2-two-sided-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Can you find interesting differences in the mean values of parameters of the dataset <strong>dat</strong> for the two groups defined by the <strong>location</strong>?
Follow these steps:</p>
<ol style="list-style-type: decimal">
<li><p>Select the two groups according to the location.
To do so, check the result of <code>distinct(location)</code> and create two tibbles corresponding to each of possible the locations.</p></li>
<li><p>Calculate the mean values of the numerical parameters for each group (ex: age, height, weight, waist, hip, …).
<em>Hint</em>: create first a dataframe with numeric columns only (use <code>select(which(is.numerical))</code>).
Select the rows corresponding to the two groups and use an <code>summarise()</code> and <code>group_by</code> loop to calculate the mean values (grouped by location).</p></li>
<li><p>Select one of these, formulate the H0 and H1 hypotheses and perform a (two-sided) t-test.
Interpret the result (alpha = 0.05).</p></li>
</ol>
</div>
<div id="exercise-3.-going-further-checking-the-normality-of-the-distribution" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Exercise 3. Going further … Checking the normality of the distribution<a href="week-1-hypothesis-testing.html#exercise-3.-going-further-checking-the-normality-of-the-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In principle, t-tests require that the data is approximately normally distributed.
If not, we can use <strong>non-parametric</strong> tests (see next lecture).</p>
<p>In order to check whether the data is normally distributed or not, it is possible to perform a <strong>Shapiro-Wilk</strong> normality test (see lecture).
This statistical test is implemented in R in the function <code>shapiro.test()</code>.</p>
<hr />
</div>
</div>
<div id="wilcoxon-test" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Wilcoxon test<a href="week-1-hypothesis-testing.html#wilcoxon-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
</div>
<div id="chi-squared-test" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Chi-squared test<a href="week-1-hypothesis-testing.html#chi-squared-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
</div>
<div id="fishers-exact-test" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Fisher’s exact test<a href="week-1-hypothesis-testing.html#fishers-exact-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-1-probability-distributions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-1-multiple-testing-and-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-hypothesis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
